### ISSUE TITLE
Develop a wireframe using Figma

### ISSUE THREAD

**Issue by Imani-ES** [NickMacris/CSE442-A5-GroupProject#26]
The Figma Website : https://www.figma.com/file/h2SqzuYZzpuNXJaOBAWnG3/CSE-442-UI-Wireframe-High-Five🖐?node-id=3%3A3

1. Go to this website via the link above
2. Click on the play button; it will lead you to a new tab with the wireframe displayed as webpage -> initially showing the Login Page Prototype
3. Click anywhere on the Login page and it will transition you to the Main Page after the Login Page.

The tutorial on how to create a wireframe: https://youtu.be/qpH7-KFWZRI

**Comment by LRich530** [comment]
These are not tests, they are the tasks you needed to complete for today. I need you to link those pages you created in Figma so that the team can access it. Try to have it completed before the meeting today.

**Comment by Imani-ES** [comment]
Was this meant to be assigned to me?
And should I edit it to say "Acceptance Tasks?"

**Comment by Imani-ES** [comment]
or should I be having each bullet point as a different task

**Comment by AshaJG** [comment]
Additional Information : 

The Figma Website : https://www.figma.com/file/h2SqzuYZzpuNXJaOBAWnG3/CSE-442-UI-Wireframe-High-Five🖐?node-id=3%3A3

The tutorial on how to create a wireframe : https://youtu.be/qpH7-KFWZRI
